// This file is automatically generated from your CSS. Any edits will be overwritten.
export const card: string;
export const image: string;
export const message: string;
export const voteButton: string;
